id: IBA800DAE
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-05-30T21:05:36.808261'
last_modified: '2022-05-30T21:05:36.808266'
parser: null
source_metadata:
  title: Jamyang Khyenrab Tayé Series
  language: bo
  description: 'Texts by and about Jamyang Khyenrab Tayé (''jam dbyangs mkhyen rab
    mtha’ yas, 1862–1937):'
  volume:
    fEF25:
      title: 'The Fresh Utpala: A Prayer to the Great Learned Teacher and Vajra-Holder
        Jamyang Khyenrab Tayé'
      base_file: fEF25.txt
      order: 1
      parent: Prayers
    f470C:
      title: Prayer for the Swift Rebirth of Jamyang Khyenrab Tayé
      base_file: f470C.txt
      order: 2
      parent: Swift Rebirth Prayers
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
